"""ondelete=CASCADE

Revision ID: 704c633ab4f4
Revises: 8ab51d4fac32
Create Date: 2023-04-20 13:56:05.268612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704c633ab4f4'
down_revision = '8ab51d4fac32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('userpermissions_user_id_fkey', 'userpermissions', type_='foreignkey')
    op.create_foreign_key(None, 'userpermissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userpermissions', type_='foreignkey')
    op.create_foreign_key('userpermissions_user_id_fkey', 'userpermissions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
